version: "2.3"
services:
  php-fpm:
    build: .docker/php-fpm
    volumes:
        - .:/var/www/html/
    volumes_from:
      - composer
    
  nginx:
    build: .docker/nginx
    ports:
        - 8088:80
    volumes:
        - .:/var/www/html/        
    links:
      - php-fpm

  composer:
    restart: 'no'
    image: composer/composer:php7
    command: install
    volumes:
      - .:/app